name: Unit Tests

on:
  pull_request:
    branches:
      - latest
      - next

  push:
    branches:
      - latest
      - next

jobs:
  unit_tests:
    name: Test that the library functions are working as expected
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: python library/brainfuck_test.py
